#!/usr/bin/env python3

from crontab import CronTab
from distutils import spawn  # For which-like function

COMMENT_ID = "LectioExporter"

tab = CronTab(user=True)

tab.remove_all(comment=COMMENT_ID)  # Clean old configs

cmd = spawn.find_executable("export_lectio")

job = tab.new(command=cmd, comment=COMMENT_ID)
job.every(15).minutes()

tab.write()

print("Crontab set up.")
print("Please run 'export_lectio' once manually "
      "to ensure credentials are stored.")
